monProjetApex/force-app/main/default/objects/Order/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Particulier</fullName>
            </value>
            <value>
                <fullName>Professionnel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

monProjetApex/force-app/main/default/objects/Order/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <description>selon pays de livraison</description>
    <label>Pays</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

monProjetApex/force-app/main/default/objects/TarifLivraison__c/TarifLivraison__c.object-meta.xml
<CustomObject>
    <label>TarifLivraison</label>
    <nameField>
        <label>TarifLivraison Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TarifLivraisons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

monProjetApex/force-app/main/default/objects/TarifLivraison__c/fields/delai__c.field-meta.xml
<CustomField>
    <fullName>delai__c</fullName>
    <label>delai</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

monProjetApex/force-app/main/default/objects/TarifLivraison__c/fields/pays__c.field-meta.xml
<CustomField>
    <fullName>pays__c</fullName>
    <label>pays</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

monProjetApex/force-app/main/default/objects/TarifLivraison__c/fields/prix__c.field-meta.xml
<CustomField>
    <fullName>prix__c</fullName>
    <label>prix</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

monProjetApex/force-app/main/default/objects/TarifLivraison__c/fields/TypeClient__c.field-meta.xml
<CustomField>
    <fullName>TypeClient__c</fullName>
    <label>TypeClient</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Particulier</fullName>
            </value>
            <value>
                <fullName>Professionnel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

monProjetApex/force-app/main/default/tests/DeliveryOrderServiceTest.cls
@isTest
private class DeliveryOrderServiceTest {

    @isTest
    static void testCreateLivraison(){

        Account acc = new Account(Name='Test');
        insert acc;

        Order ord = new Order(
            AccountId = acc.Id,
            Status='Activated',
            EffectiveDate = Date.today(),
            Pays__c = 'France',
            Account_Type__c = 'Particulier'
        );
        insert ord;

        TarifLivraison__c tarif = new TarifLivraison__c(
            Name='Test Tarif',
            Prix__c=10,
            Delai__c=2,
            Pays__c='France',
            TypeClient__c='Particulier'
        );
        insert tarif;

        Map<Id,Id> selectedTarifs = new Map<Id,Id>();
        selectedTarifs.put(ord.Id,tarif.Id);

        Test.startTest();

        Map<Id,Id> result = DeliveryOrderService.createByOrderIds(
            new List<Id>{ord.Id},
            selectedTarifs
        );

        Test.stopTest();

        System.assert(result.containsKey(ord.Id));

    }

}