monProjetApex/force-app/main/default/objects/Order/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Particulier</fullName>
            </value>
            <value>
                <fullName>Professionnel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

monProjetApex/force-app/main/default/objects/Order/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <description>selon pays de livraison</description>
    <label>Pays</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

monProjetApex/force-app/main/default/objects/Order/fields/Transporteur__c.field-meta.xml
<CustomField>
    <fullName>Transporteur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transporteur</label>
    <referenceTo>Transporteur__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

monProjetApex/force-app/main/default/objects/TarifLivraison__c/TarifLivraison__c.object-meta.xml
<CustomObject>
    <label>TarifLivraison</label>
    <nameField>
        <label>TarifLivraison Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TarifLivraisons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

monProjetApex/force-app/main/default/objects/TarifLivraison__c/fields/delai__c.field-meta.xml
<CustomField>
    <fullName>delai__c</fullName>
    <label>delai</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

monProjetApex/force-app/main/default/objects/TarifLivraison__c/fields/pays__c.field-meta.xml
<CustomField>
    <fullName>pays__c</fullName>
    <label>pays</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

monProjetApex/force-app/main/default/objects/TarifLivraison__c/fields/prix__c.field-meta.xml
<CustomField>
    <fullName>prix__c</fullName>
    <label>prix</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

monProjetApex/force-app/main/default/objects/TarifLivraison__c/fields/Transporteur__c.field-meta.xml
<CustomField>
    <fullName>Transporteur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transporteur</label>
    <referenceTo>Transporteur__c</referenceTo>
    <relationshipLabel>TarifLivraisons</relationshipLabel>
    <relationshipName>TarifLivraisons</relationshipName>
    <type>Lookup</type>
</CustomField>

monProjetApex/force-app/main/default/objects/TarifLivraison__c/fields/TypeClient__c.field-meta.xml
<CustomField>
    <fullName>TypeClient__c</fullName>
    <label>TypeClient</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Particulier</fullName>
            </value>
            <value>
                <fullName>Professionnel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

monProjetApex/force-app/main/default/objects/Transporteur__c/Transporteur__c.object-meta.xml
<CustomObject>
    <label>Transporteur</label>
    <nameField>
        <label>Transporteur Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transporteurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

monProjetApex/force-app/main/default/objects/Transporteur__c/fields/TypeClient__c.field-meta.xml
<CustomField>
    <fullName>TypeClient__c</fullName>
    <label>TypeClient</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Particulier</fullName>
            </value>
            <value>
                <fullName>Professionnel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

monProjetApex/force-app/main/default/classes/services/TarifLivraisonService.cls
public with sharing class TarifLivraisonService {

    @AuraEnabled(cacheable=true)
    public static List<TarifLivraison__c> getTarifLivraison(Id orderId){

        // Récupérer la commande
        Order ord = [
            SELECT Id, Pays__c, Account_Type__c
            FROM Order
            WHERE Id = :orderId
            LIMIT 1
        ];

        // Récupérer les tarifs correspondants
        return [
            SELECT Id,
                   Prix__c,
                   Delai__c,
                   Transporteur__r.Id,
                   Transporteur__r.Name,
                   Transporteur__r.TypeClient__c
            FROM TarifLivraison__c
            WHERE Pays__c = :ord.Pays__c
            AND TypeClient__c = :ord.Account_Type__c
            ORDER BY Prix__c ASC
        ];
    }
}