monProjetApex/force-app/main/default/objects/Order/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Particulier</fullName>
            </value>
            <value>
                <fullName>Professionnel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

monProjetApex/force-app/main/default/objects/Order/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <description>selon pays de livraison</description>
    <label>Pays</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

monProjetApex/force-app/main/default/objects/TarifLivraison__c/TarifLivraison__c.object-meta.xml
<CustomObject>
    <label>TarifLivraison</label>
    <nameField>
        <label>TarifLivraison Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TarifLivraisons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

monProjetApex/force-app/main/default/objects/TarifLivraison__c/fields/pays__c.field-meta.xml
<CustomField>
    <fullName>pays__c</fullName>
    <label>pays</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

monProjetApex/force-app/main/default/tests/TarifLivraisonServiceTest.cls
@isTest
private class TarifLivraisonServiceTest {

    @isTest
    static void testGetTarifs(){

        Account acc = new Account(Name='Test');
        insert acc;

        Order ord = new Order(
            AccountId = acc.Id,
            Status='Activated',
            EffectiveDate=Date.today(),
            Pays__c='France',
            Account_Type__c='Particulier'
        );

        insert ord;

        Test.startTest();

        List<TarifLivraison__c> tarifs = TarifLivraisonService.getTarifs(ord.Id);

        Test.stopTest();

        System.assertNotEquals(null,tarifs);

    }
}