monProjetApex/force-app/main/default/objects/Livraison__c/Livraison__c.object-meta.xml
<CustomObject>
    <label>Livraison</label>
    <nameField>
        <label>Livraison Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Livraisons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

monProjetApex/force-app/main/default/objects/Livraison__c/fields/DateExpedition__c.field-meta.xml
<CustomField>
    <fullName>DateExpedition__c</fullName>
    <label>DateExpedition</label>
    <type>Date</type>
</CustomField>

monProjetApex/force-app/main/default/objects/Livraison__c/fields/DateLivraisonEstimee__c.field-meta.xml
<CustomField>
    <fullName>DateLivraisonEstimee__c</fullName>
    <label>DateLivraisonEstimee</label>
    <type>Date</type>
</CustomField>

monProjetApex/force-app/main/default/objects/Livraison__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Livraisons</relationshipLabel>
    <relationshipName>Livraisons</relationshipName>
    <type>Lookup</type>
</CustomField>

monProjetApex/force-app/main/default/objects/Livraison__c/fields/statut__c.field-meta.xml
<CustomField>
    <fullName>statut__c</fullName>
    <label>statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En préparation</fullName>
            </value>
            <value>
                <fullName>Expédiée</fullName>
            </value>
            <value>
                <fullName>Livrée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

monProjetApex/force-app/main/default/objects/Livraison__c/fields/Transporteur__c.field-meta.xml
<CustomField>
    <fullName>Transporteur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transporteur</label>
    <referenceTo>Transporteur__c</referenceTo>
    <relationshipLabel>Livraisons</relationshipLabel>
    <relationshipName>Livraisons</relationshipName>
    <type>Lookup</type>
</CustomField>

monProjetApex/force-app/main/default/objects/Order/fields/Transporteur__c.field-meta.xml
<CustomField>
    <fullName>Transporteur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transporteur</label>
    <referenceTo>Transporteur__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

monProjetApex/force-app/main/default/objects/Transporteur__c/Transporteur__c.object-meta.xml
<CustomObject>
    <label>Transporteur</label>
    <nameField>
        <label>Transporteur Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transporteurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

monProjetApex/force-app/main/default/classes/managers/LivraisonManager.cls
public with sharing class LivraisonManager {

    @AuraEnabled
    public static Livraison__c createLivraison(Id orderId) {

        Order ord = [
            SELECT Id, ShippingCountry, Account.Type
            FROM Order
            WHERE Id = :orderId
        ];

        OrderService.validateOrder(ord);

        Transporteur__c t = LivraisonService.getBestTransporteur(
            ord.ShippingCountry,
            ord.Account.Type
        );

        Livraison__c liv = new Livraison__c(
            Order__c = ord.Id,
            Transporteur__c = t.Id,
            Statut__c = 'En préparation',
            DateExpedition__c = System.today(),
            DateLivraisonEstimee__c = System.today().addDays(3)
        );

        insert liv;
        return liv;
    }
}